# Generated by Django 2.1.7 on 2019-03-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190302_1433'),
    ]

    operations = [
    ]
