# Generated by Django 2.1.7 on 2019-03-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190302_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('_id', models.CharField(max_length=256, unique=True)),
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('guid', models.CharField(max_length=128, unique=True)),
                ('has_died', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('picture', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('registered', models.DateTimeField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('favourite_food', models.TextField(blank=True, null=True)),
                ('favourite_fruit', models.TextField(blank=True, null=True)),
                ('favourite_vegetable', models.TextField(blank=True, null=True)),
                ('greeting', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='friend_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='api.People'),
        ),
        migrations.AddField(
            model_name='friend',
            name='people_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.People'),
        ),
    ]
